name: create-mcf-json

on: [workflow_dispatch]

jobs:
  create-formula:
    name: create mcf json for scoop
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Generate mcf json for scoop
      shell: bash
      run: chmod +x scripts/binaries/mcf && ./scripts/binaries/mcf > bucket/mcf.json
    - name: Commit mcf json for scoop
      run: |
        git config --global user.name 'Github create-formula action'
        git config --global user.email '43384430+mdpadberg@users.noreply.github.com'
        git add bucket/mcf.json
        git commit -m "New mcf json for scoop"
        git push 